import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { RoleCredentialStatus, RoleStatus } from 'passport-did-auth';
import { PinoLogger } from 'nestjs-pino';

@Injectable()
export class RolesValidationService {
  constructor(
    private readonly configService: ConfigService,
    private readonly logger: PinoLogger,
  ) {
    this.logger.setContext(RolesValidationService.name);
  }

  /**
   * Checks if all valid roles included in the access token generated by the passport-did-auth are listed in the ACCEPTED_ROLES.
   * This is required to protect against intermittent problem when user is being logged in but token roles are inconsistent.
   */
  public async didAccessTokenRolesAreValid(
    userRoles: RoleStatus[],
  ): Promise<boolean> {
    const acceptedRoles = this.configService
      .get('ACCEPTED_ROLES', '')
      .split(',')
      .filter(Boolean);

    if (acceptedRoles.length === 0) {
      this.logger.error(`acceptedRoles is empty`);
      return false;
    }

    const roles = userRoles
      .filter((role) => role.status === RoleCredentialStatus.VALID)
      .map((r) => r.namespace);

    this.logger.debug(
      `validating ${JSON.stringify(roles)} against ${JSON.stringify(
        acceptedRoles,
      )}`,
    );

    return roles.some((r) => acceptedRoles.includes(r));
  }
}
