version: "3.8"

services:
  webserver:
    restart: unless-stopped
    image: bitnami/nginx:1.23
    ports:
      - "127.0.0.1:8080:80"
    networks:
      backend:
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./nginx/nginx.gp4btc.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.conf

  auth-server:
    depends_on:
      - redis
    restart: unless-stopped
    image: did-auth-proxy-auth-server
    pull_policy: never
    build:
      context: authorization-server
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - SELF_BASE_URL=http://127.0.0.1:3000
      - SWAGGER_PATH=api-auth
      - PORT=80
      - CORS_MAX_AGE=60
      - CORS_ORIGIN=http://localhost:3001
      - RPC_URL=https://volta-rpc.energyweb.org/
      - CACHE_SERVER_URL=https://identitycache-dev.energyweb.org/v1
      - CACHE_SERVER_LOGIN_PRVKEY=eab5e5ccb983fad7bf7f5cb6b475a7aea95eff0c6523291b0c0ae38b5855459c
      - DID_REGISTRY_ADDRESS=0xc15d5a57a8eb0e1dcbe5d88b8f9a82017e5cc4af
      - ENS_REGISTRY_ADDRESS=0xd7CeF70Ba7efc2035256d828d5287e2D285CD1ac
      - ENS_RESOLVER_ADDRESS=0xcf72f16Ab886776232bea2fcf3689761a0b74EfE
      - IPFS_PROTOCOL=https
      - IPFS_HOST=ipfs.io
      - IPFS_PORT=443
#      - IPFS_PROJECTID=<put-your-value-here>
#      - IPFS_PROJECTSECRET=<put-your-value-here>
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - JWT_SECRET=asecretstring
      - BLOCKNUM_AUTH_ENABLED=true
      - ACCEPTED_ROLES=
      - INCLUDE_ALL_ROLES=true
      - JWT_ACCESS_TTL=3600
      - JWT_REFRESH_TTL=86400
      - SIWE_NONCE_TTL=300
      - AUTH_COOKIE_NAME_ACCESS_TOKEN=token
      - AUTH_COOKIE_NAME_REFRESH_TOKEN=refreshToken
      - AUTH_COOKIE_ENABLED=false
      - AUTH_COOKIE_SECURE=true
    networks:
      backend:

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      backend:
    volumes:
      - dev-redis-data:/bitnami/redis/data

volumes:
  dev-redis-data:

networks:
  backend:
