name: Build and Push Docker Image

on:
  push:
    branches: [push-to-ghcr]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build & Push Image'
      run: |
        docker build -t ghcr.io/energywebfoundation/did-auth-proxy:${{ github.sha }} -f authorization-server/Dockerfile ./authorization-server
        docker push ghcr.io/energywebfoundation/did-auth-proxy:${{ github.sha }}
        
